port: 8080
context-path: /
mock: ~/workspace/personal/backend/mock-server/dev/mock
redirect:
  url: https://jsonplaceholder.typicode.com
  log-enabled: true
  store-responses-dir: ./.temp/
  replacement:
    - old: mock-server
      new: ""
