name: Build Validation

on:
  push:
    branches:
      - "*"

jobs:
  validation:
    name: "Test Run"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.4
      - name: Test Run
        run: |
          go test


